name: buildx

on:
  push:
    branches: master
    tags:

jobs:
  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.5
      with:
        version: latest
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Change for master
      id: change_version
      run: if [ "$steps.get_version.outputs.VERSION" == "master" ]; then echo ::set-output name=VERSION::latest; else echo ::set-output name=VERSION::${{ steps.get_version.outputs.VERSION }}; fi
    - name: Available platforms
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --output "type=image,push=true" \
          -t cyberrebooot/pcapplot:${{ steps.change_version.outputs.VERSION }} .
