name: buildx

on:
  push:
    branches: master
    tags:

jobs:
  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.5
      with:
        version: latest
    - name: Available platforms
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          .
